### PR TITLE
Add support for timeout in RelayNode and make easier to use classes with a i2c PortExpander

### PR DESCRIPTION
**Pull request by ivanfmartinez**
add support for timeout in RelayNodes

refactor Relay and Contact Nodes, separing the physical pin access and make possible to use extend this classes to use with i2c portexpanders.

### CODE REVIEW

**Comment by kleini** [comment]
Do you have an example, how to use it with I²C port expanders?

**Comment by ivanfmartinez** [comment]
Here are the example : https://github.com/ivanfmartinez/PortExpander_I2C_Nodes

It was tested with this board (made by an Brazilian company) : https://www.afeletronica.com.br/pd-4d1faf-esp-8266-modulo-afsmart-7-reles.html?ct=1d09d1&p=1&s=1

**Comment by kleini** [comment]
@ivanfmartinez Nice board and example! Where does the PortExpander_I2C.h come from?

**Comment by ivanfmartinez** [comment]
I got from the board manufacturer but I have checked and its the same from this article : http://blog.iharder.net/2014/08/08/msp430-or-arduino-library-for-pcf8574-i2c-port-expander/

**Comment by luebbe** [comment]
Very nice!
I'll merge it, when I'm back home in a week.

**Comment by luebbe** [comment]
Could you please resolve the conflicts and update the PR?

**Comment by ivanfmartinez** [comment]
I have merged all my changes in a single PR #7

**Comment by luebbe** [comment]
Merged updated PR #7 instead

**Pull request closed without merging**
